name: restaurants-api-cd

on:
  workflow_run:
    workflows: ["restaurants-api-ci"]
    types:
      - completed

jobs:
  deploy_dev:
    name: Deploy â†’ Dev
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment:
      name: Dev

    steps:
      - name: Download artifact from build workflow
        uses: actions/download-artifact@v4
        with:
          name: Api-Artifact
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to Azure Web App (Dev)
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'restaurants-api-dev'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          package: .
